# Generated by Django 5.1.6 on 2025-02-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account_loancustomer_loanprovider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('LP', 'LoanProvider'), ('LC', 'Loan'), ('BK', 'Bank')], default='LP', max_length=2),
        ),
    ]
