# Generated by Django 5.1.6 on 2025-02-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('LP', 'LoanProvider'), ('LC', 'Loan'), ('BK', 'Bank')], max_length=2),
        ),
    ]
