# Generated by Django 5.1.6 on 2025-02-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_monthlyrepayment_over_due'),
        ('users', '0006_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancustomer',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_plan', to='loan.loanplan'),
        ),
    ]
