# Generated by Django 5.1.6 on 2025-02-23 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_loan_duration', models.IntegerField()),
                ('min_loan_duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('PD', 'Paid')], default='P', max_length=10)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_duration', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_repayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_repayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_taken', to=settings.AUTH_USER_MODEL)),
                ('loan_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
