# Generated by Django 5.1.6 on 2025-02-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_loan_status_loanrequest'),
        ('users', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_customer', to='users.loancustomer'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_provider', to='users.loanprovider'),
        ),
    ]
