# Generated by Django 5.1.6 on 2025-02-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_alter_loan_loan_customer_alter_loan_loan_provider'),
        ('users', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans_provider', to='users.loanprovider'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('RQ', 'Requested'), ('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('PD', 'Paid')], default='RQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monthly_repayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_repayment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
