# Generated by Django 5.1.6 on 2025-02-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_loan_interest_rate_alter_loan_loan_provider_and_more'),
        ('users', '0003_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loans_provider', to='users.loanprovider'),
        ),
    ]
