# Generated by Django 5.1.6 on 2025-02-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_monthlyrepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyrepayment',
            old_name='month',
            new_name='date',
        ),
        migrations.AddField(
            model_name='loanplan',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlyrepayment',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
