# Generated by Django 5.1.6 on 2025-02-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_rename_month_monthlyrepayment_date_loanplan_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanplan',
            name='allowness_period',
            field=models.IntegerField(default=0),
        ),
    ]
