# Generated by Django 5.1.6 on 2025-02-25 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_loanplan_allowness_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanplan',
            name='allowness_period',
        ),
        migrations.AddField(
            model_name='loanplan',
            name='allowness',
            field=models.IntegerField(default=True),
        ),
    ]
