# Generated by Django 5.1.6 on 2025-02-25 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_remove_loanplan_allowness_period_loanplan_allowness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanplan',
            old_name='penalty',
            new_name='penalty_amount',
        ),
    ]
