# Generated by Django 5.1.6 on 2025-02-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0011_rename_penalty_loanplan_penalty_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrepayment',
            name='over_due',
            field=models.BooleanField(default=False),
        ),
    ]
